server.port=8080
bmi.template=Mit einem Gewicht von %.2f kg und einer Größe von %.2f cm  hat %s einen BMI von %.2f und ist damit %s.
bmi.underweight_limit=18.0
bmi.normalweight_limit=25.0
bmi.overweight_limit=28.0
bmi.underweight=untergewichtig
bmi.normalweight=normalgewichtig
bmi.overweight=übergewichtig
bmi.obese=fettleibig
