server.port=8080
bmi.template=with a weight of %.2f kg and a height of %.2f cm  %s has a body mass index of %.2f and is %s.
bmi.underweight_limit=18.0
bmi.normalweight_limit=25.0
bmi.overweight_limit=28.0
bmi.underweight=underweight
bmi.normalweight=normal weight
bmi.overweight=overweight
bmi.obese=obese
todos.illegalIndexTemplate=invalid index %d, must be between 0 and %d 
todos.elementTemplate=your todo at index %d is %s 
todos.removeElementTemplate=your todo %s at index %d is removed 
todos.addElementTemplate=your todo %s was added 
todos.clearTemplate=your todo list was cleared 
